### ISSUE TITLE
Missing support for json input files

### ISSUE THREAD

**Issue by gicao** [benhoyt/goawk#196] opened 2023-07-13 16:24 UTC
Is it possible to add support for json input?
The script writer could refer to fields in the json input using json-path like syntax.

**Comment by benhoyt** [comment] 2023-07-13 22:45
Closing as this is a duplicate of https://github.com/benhoyt/goawk/issues/152 -- this is something I'd like to do, but need to find time to spec it out fully and then implement it. Feel free to comment there if you have specifics to add to the discussion. Thanks!

**Closed by benhoyt** 2023-07-13 22:45 UTC
