### ISSUE TITLE
Inconsistency in array keys iteration order

### ISSUE THREAD

**Issue by xonixx** [benhoyt/goawk#72] opened 2021-10-24 13:12 UTC
I'm not sure if this can be called a bug or feature, but at least this is where GoAWK differs from major implementations.

```awk
BEGIN {
  arr["a"];arr["b"];arr["c"];arr["d"];arr["e"]
  arr["f"];arr["g"];arr["h"];arr["i"];arr["j"]
  for (k in arr) printf k
  print ""
}
```

The output order is always same among runs under bwk, gawk, mawk.

It changes from run to run under GoAWK. 

Encountered this in https://github.com/xonixx/makesure/issues/73.

**Comment by benhoyt** [comment] 2021-12-22 22:54
I've also considered implementing my own GoAWK-specific hash table for efficiency reasons, and that would almost certainly have a consistent iteration order across multiple iterations (though would still probably be un-ordered).

**Comment by benhoyt** [comment] 2022-01-03 10:54
I'm going to close this for now. Iteration order is unspecified according to POSIX, so it's not a bug (I guess it could even be considered a feature: like Go's map, the random iteration order means that tests or scripts that depend on a specific order will be noticed quickly).

Regarding the above comment: I did try implementing a quick-n-dirty custom hash table (see the [custom-array branch](https://github.com/benhoyt/goawk/compare/custom-array)), but the speed improvement was only about 5% for a real-world, array-heavy script, so it doesn't seem worth the complexity at the moment. So I'm not going that route either.

**Closed by benhoyt** 2022-01-03 10:54 UTC
Labels: feature
